import assert from "node:assert/strict";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { format } from "prettier";
import { keccak256 } from "viem";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const readJson = (file) => JSON.parse(readFileSync(join(root, file), "utf8"));
const check = process.argv.includes("--check");
const source = readJson("deployments/mining-inputs.json");
const release = readJson("deployments/deterministic-release.json");
const generatedComment =
  "/** Generated by scripts/generateAbi.mjs. Do not edit manually. */";

function minParam(p) {
  const m = { name: p.name || "", type: p.type };
  if (p.components) m.components = p.components.map(minParam);
  if (p.indexed) m.indexed = true;
  return m;
}

function minimalAbi(entry) {
  const m = { type: entry.type };

  if (
    entry.name &&
    !["constructor", "fallback", "receive"].includes(entry.type)
  ) {
    m.name = entry.name;
  }

  // Keep empty arrays: viem and abitype require inputs (and function outputs) to be present.
  if (entry.inputs) m.inputs = entry.inputs.map(minParam);

  if (entry.outputs) {
    m.outputs = entry.outputs.map((o) => {
      const out = { type: o.type };
      if (o.name) out.name = o.name;
      if (o.components) out.components = o.components.map(minParam);
      return out;
    });
  }

  // abitype requires stateMutability on functions, constructors, fallback, and receive.
  if (entry.stateMutability) m.stateMutability = entry.stateMutability;

  if (entry.anonymous) m.anonymous = true;

  return m;
}

function filterAbi(abi) {
  const seen = new Set();
  const ozErrors = [
    "ERC20InsufficientBalance",
    "ERC20InvalidSender",
    "ERC20InvalidReceiver",
    "ERC20InsufficientAllowance",
    "ERC20InvalidApprover",
    "ERC20InvalidSpender",
    "OwnableUnauthorizedAccount",
    "OwnableInvalidOwner",
  ];
  const skipEvents = ["OwnershipTransferred"];
  const skipFuncs = [
    "supportsInterface",
    "_msgSender",
    "_msgData",
    "_contextSuffixLength",
  ];

  return abi.filter((e) => {
    if (["constructor", "fallback", "receive"].includes(e.type)) return true;

    if (e.type === "event") {
      if (["Transfer", "Approval"].includes(e.name)) return true;
      if (skipEvents.includes(e.name)) return false;
      return true;
    }

    if (e.type === "error") {
      if (ozErrors.includes(e.name)) return false;
      return true;
    }

    if (e.type === "function") {
      const sig = `${e.name}(${(e.inputs || []).map((i) => i.type).join(",")})`;
      if (seen.has(sig)) return false;
      seen.add(sig);
      if (skipFuncs.includes(e.name)) return false;
      return true;
    }

    return true;
  });
}

async function main() {
  const revision = spawnSync(
    "git",
    ["-C", join(root, "foundry"), "rev-parse", "HEAD"],
    { encoding: "utf8" },
  );
  assert.equal(revision.status, 0, "Cannot read the frozen contracts revision");
  assert.equal(
    revision.stdout.trim(),
    source.sourceCommit,
    "Contracts pin differs from the release source",
  );
  const artifacts = Object.fromEntries(
    ["Factory", "Option", "Receipt", "OptionUtils", "FactoryDeployer"].map(
      (name) => [name, readJson(`out/${name}.sol/${name}.json`)],
    ),
  );
  assert.equal(
    keccak256(artifacts.Factory.bytecode.object),
    release.initCodeHash,
    "Rebuild root out/ with the frozen compiler settings and linked OptionUtils",
  );
  const contracts = Object.fromEntries(
    Object.entries(artifacts).map(([name, artifact]) => [
      name,
      { abi: filterAbi(artifact.abi).map(minimalAbi), inheritedFunctions: {} },
    ]),
  );
  const abiSource = {
    releaseTag: source.releaseTag,
    sourceCommit: source.sourceCommit,
    initCodeHash: release.initCodeHash,
  };
  const target = join(root, "src/generated");
  const result = await format(
    `
    ${generatedComment}
    export const abiSource = ${JSON.stringify(abiSource)} as const;
    export const contracts = ${JSON.stringify(contracts)} as const;
  `,
    { parser: "typescript" },
  );
  const file = join(target, "abi.ts");
  if (check)
    assert.equal(readFileSync(file, "utf8"), result, `Out of sync: ${file}`);
  else {
    mkdirSync(target, { recursive: true });
    writeFileSync(file, result);
  }
  console.log(
    `${check ? "Checked" : "Generated"} shared ABIs for ${source.releaseTag}`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
