import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { format } from "prettier";
import { decodeEventLog, getAddress, keccak256 } from "viem";
import { contracts, abiSource } from "../src/generated/abi.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const readJson = (file) => JSON.parse(readFileSync(join(root, file), "utf8"));
const source = readJson("deployments/mining-inputs.json");
const release = readJson("deployments/deterministic-release.json");
const comment =
  "/** Generated by scripts/registerDeployment.mjs. Do not edit manually. */";

export function readDeployment(run, chainId, name) {
  assert(
    Number.isSafeInteger(chainId) && chainId > 0,
    "Expected a positive chain ID",
  );
  assert.match(
    name,
    /^[a-z][a-zA-Z0-9]*$/,
    "Chain name must be a filename-safe identifier",
  );
  assert.equal(
    Number(run.chain),
    chainId,
    "Broadcast chain does not match the destination",
  );
  assert.equal(
    run.pending?.length ?? 0,
    0,
    "Broadcast still has pending transactions",
  );
  const receipts = [...run.receipts].sort(
    (a, b) => Number(b.blockNumber) - Number(a.blockNumber),
  );
  for (const receipt of receipts) {
    if (Number(receipt.status) !== 1) continue;
    for (const log of receipt.logs) {
      if (log.address.toLowerCase() !== source.deployer.toLowerCase()) continue;
      const event = decodeEventLog({
        abi: contracts.FactoryDeployer.abi,
        ...log,
      });
      if (event.eventName !== "Deployed") continue;
      assert.equal(
        getAddress(event.args.factory),
        getAddress(release.factory),
        "Wrong release Factory",
      );
      assert.equal(
        event.args.owner.toLowerCase(),
        release.owner.toLowerCase(),
        "Wrong release owner",
      );
      assert.equal(event.args.salt, release.salt, "Wrong release salt");
      const tx = run.transactions.find(
        (t) => t.hash === receipt.transactionHash,
      );
      assert(tx, "Missing Factory transaction");
      assert.equal(
        Number(tx.transaction.chainId),
        chainId,
        "Transaction chain mismatch",
      );
      const created = Object.fromEntries(
        (tx.additionalContracts ?? []).map((c) => [c.contractName, c]),
      );
      assert(
        created.Factory?.initCode &&
          created.Option?.address &&
          created.Receipt?.address,
        "Broadcast is missing the Factory or clone creation trace",
      );
      assert.equal(
        keccak256(created.Factory.initCode),
        abiSource.initCodeHash,
        "Deployment does not match the shared ABI build",
      );
      assert.equal(
        getAddress(created.Factory.address),
        getAddress(release.factory),
      );
      const templates = Object.fromEntries(
        ["Option", "Receipt"].map((key) => [
          key,
          getAddress(created[key].address),
        ]),
      );
      const deployerTx = run.transactions.find(
        (t) =>
          t.transactionType === "CREATE2" &&
          t.contractAddress.toLowerCase() === source.deployer.toLowerCase(),
      );
      if (deployerTx)
        assert(
          run.receipts.some(
            (r) =>
              r.transactionHash === deployerTx.hash && Number(r.status) === 1,
          ),
          "FactoryDeployer transaction is not confirmed",
        );
      return {
        templates,
        chain: {
          name,
          deploymentBlock: Number(receipt.blockNumber),
          ...(deployerTx ? { deployerTransaction: deployerTx.hash } : {}),
          factoryTransaction: receipt.transactionHash,
        },
      };
    }
  }
  throw new Error("No successful Factory deployment in this broadcast");
}

async function main() {
  const { values, positionals } = parseArgs({
    allowPositionals: true,
    options: {
      all: { type: "boolean" },
      check: { type: "boolean" },
      broadcast: { type: "string" },
    },
  });
  assert(
    values.all
      ? positionals.length === 0 && !values.broadcast
      : positionals.length === 2,
    "Usage: node scripts/registerDeployment.mjs <chainId> <name> [--broadcast file] [--check], or --all [--check]",
  );
  assert.equal(
    abiSource.sourceCommit,
    source.sourceCommit,
    "Generate the shared ABI for the current release first",
  );
  assert.equal(
    abiSource.initCodeHash,
    release.initCodeHash,
    "Shared ABI build differs from the release",
  );
  assert.equal(
    abiSource.releaseTag,
    source.releaseTag,
    "Shared ABI release tag differs",
  );
  assert.match(source.releaseTag, /^[a-zA-Z0-9._-]+$/, "Invalid release tag");
  const manifestPath = `deployments/${source.releaseTag}.json`;
  const deployed = existsSync(join(root, manifestPath))
    ? readJson(manifestPath)
    : { chains: {} };
  const destinations = values.all
    ? Object.entries(deployed.chains).map(([id, chain]) => [
        Number(id),
        chain.name,
      ])
    : [[Number(positionals[0]), positionals[1]]];
  assert(
    destinations.length > 0,
    "No chains registered; pass a chain ID and name first",
  );
  for (const [id, name] of destinations) {
    const file = values.broadcast
      ? resolve(values.broadcast)
      : join(root, `broadcast/DeployDeterministic.s.sol/${id}/run-latest.json`);
    const result = readDeployment(
      JSON.parse(readFileSync(file, "utf8")),
      id,
      name,
    );
    if (deployed.templates)
      assert.deepEqual(
        result.templates,
        deployed.templates,
        "Clone templates differ across chains",
      );
    deployed.templates = result.templates;
    deployed.chains[id] = result.chain;
  }
  const entries = Object.entries(deployed.chains).sort(
    ([a], [b]) => Number(a) - Number(b),
  );
  assert.equal(
    new Set(entries.map(([, chain]) => chain.name)).size,
    entries.length,
    "Duplicate chain names",
  );
  const addresses = {
    Factory: release.factory,
    ...deployed.templates,
    OptionUtils: source.optionUtils,
    FactoryDeployer: source.deployer,
  };
  const files = new Map();
  const json = (file, value) =>
    files.set(file, JSON.stringify(value, null, 2) + "\n");
  json(manifestPath, {
    templates: deployed.templates,
    chains: Object.fromEntries(entries),
  });
  for (const [id, chain] of entries) {
    assert.match(chain.name, /^[a-z][a-zA-Z0-9]*$/);
    json(`deployments/${id}.json`, {
      networkName: chain.name,
      ...Object.fromEntries(
        Object.entries(addresses).map(([name, address]) => [address, name]),
      ),
    });
  }
  files.set(
    "src/generated/deployments.ts",
    await format(
      `
    ${comment}
    export const RELEASE = ${JSON.stringify({
      release: source.releaseTag,
      factory: release.factory,
      optionTemplate: deployed.templates.Option,
      receiptTemplate: deployed.templates.Receipt,
      optionUtils: source.optionUtils,
      factoryDeployer: source.deployer,
    })} as const;
    /** First block with the Factory, by chain id. */
    export const DEPLOYMENT_BLOCKS: Record<number, number> = ${JSON.stringify(
      Object.fromEntries(entries.map(([id, chain]) => [id, chain.deploymentBlock])),
    )};
  `,
      { parser: "typescript" },
    ),
  );
  if (values.check) {
    for (const [file, text] of files)
      assert.equal(
        readFileSync(join(root, file), "utf8"),
        text,
        `Out of sync: ${file}`,
      );
  } else {
    for (const [file, text] of files) {
      mkdirSync(dirname(join(root, file)), { recursive: true });
      if (
        !existsSync(join(root, file)) ||
        readFileSync(join(root, file), "utf8") !== text
      )
        writeFileSync(join(root, file), text);
    }
  }
  console.log(
    `${values.check ? "Checked" : "Registered"} ${destinations.map(([id, name]) => `${name} (${id})`).join(", ")}.`,
  );
}

if (
  process.argv[1] &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  main().catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
